@startuml
left to right direction
"Manager" as Manager
"Cashier" as Cashier

Manager --> (Books management)
(Books management) --> (Add new book)
(Books management) --> (List all books)

' (Books management) .> (Search books)
' (Books management) .> (Update books info)
' (Books management) .> (Delete books)
Manager --> (Receipt management\nSearch, View details)
Manager --> (Sales statistics\nRevenue, Revenue plot, Top selling)
Manager --> (Cashier accounts management\nAdd, List all, Update, Delete)
Manager --> (Sign In\nSign Out)

Cashier --> (Profile management\nView detail, Update)
Cashier --> (Create receipt\nAdd, Edit items, Delete items)
Cashier --> (Search books)
Cashier --> (Export receipt to pdf file)
Cashier --> (Sign In\nSign Out)

@enduml